import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
// import db from "../lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/nextThemeProvider";
import { cn } from "@/lib/utils";
import db from "@/lib/supabase/db";
db;

const SourceSans3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          SourceSans3.className,
          "bg-brand-light text-brand-secondary-500"
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
